"""data03_create_analysis_log_cache_tables

Revision ID: 7fcfedaf81ac
Revises: 7cc4beb68c4d
Create Date: 2026-08-03 16:25:45.578619

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fcfedaf81ac"
down_revision: str | Sequence[str] | None = "7cc4beb68c4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_link_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("riot_id_hash", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("match_id", sa.String(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patch_detection_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patch_version_before", sa.String(), nullable=False),
        sa.Column("patch_version_after", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "puuid_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(), nullable=False),
        sa.Column("puuid", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    op.create_table(
        "chat_answer_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    op.create_table(
        "chat_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("user_query", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(), nullable=False),
        sa.Column(
            "retrieved_doc_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cold_start", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ragas_eval_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eval_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sample_query", sa.Text(), nullable=False),
        sa.Column("faithfulness_score", sa.Float(), nullable=False),
        sa.Column("answer_relevancy_score", sa.Float(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "link_click_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("chat_log_id", sa.Integer(), nullable=True),
        sa.Column("target_page", sa.String(), nullable=False),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_log_id"],
            ["chat_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("puuid", sa.String(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("comp_deviation", sa.Float(), nullable=False),
        sa.Column("item_concentration", sa.Float(), nullable=False),
        sa.Column("augment_synergy", sa.Float(), nullable=False),
        sa.Column("matched_comp_id", sa.Integer(), nullable=True),
        sa.Column("coaching_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_comp_id"],
            ["comps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_analyses")
    op.drop_table("link_click_events")
    op.drop_table("ragas_eval_results")
    op.drop_table("chat_logs")
    op.drop_table("chat_answer_cache")
    op.drop_table("puuid_cache")
    op.drop_table("patch_detection_runs")
    op.drop_table("account_link_events")
    # ### end Alembic commands ###
