"""data01_create_static_tables

Revision ID: 587df19bbeec
Revises:
Create Date: 2026-08-03 16:13:06.959383

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "587df19bbeec"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "augments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("name_kr", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_legend_related", sa.Boolean(), nullable=False),
        sa.Column("riot_augment_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "champions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("riot_champion_id", sa.String(), nullable=False),
        sa.Column("name_kr", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("name_kr", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("riot_item_id", sa.String(), nullable=False),
        sa.Column(
            "components", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "traits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("name_kr", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column(
            "tier_thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "champion_traits",
        sa.Column("champion_id", sa.Integer(), nullable=False),
        sa.Column("trait_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trait_id"],
            ["traits.id"],
        ),
        sa.PrimaryKeyConstraint("champion_id", "trait_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("champion_traits")
    op.drop_table("traits")
    op.drop_table("items")
    op.drop_table("champions")
    op.drop_table("augments")
    op.drop_table("patches")
    # ### end Alembic commands ###
