"""data02_create_meta_comp_tables

Revision ID: 7cc4beb68c4d
Revises: 587df19bbeec
Create Date: 2026-08-03 16:21:33.088217

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cc4beb68c4d"
down_revision: str | Sequence[str] | None = "587df19bbeec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tier_rank", sa.String(), nullable=False),
        sa.Column("avg_place", sa.Float(), nullable=False),
        sa.Column("play_rate", sa.Float(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("playstyle_text", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "champion_item_builds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("champion_id", sa.Integer(), nullable=False),
        sa.Column("patch_version", sa.String(), nullable=False),
        sa.Column(
            "item_combination", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("play_rate", sa.Float(), nullable=False),
        sa.Column("avg_place", sa.Float(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patch_version"],
            ["patches.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comp_augments",
        sa.Column("comp_id", sa.Integer(), nullable=False),
        sa.Column("augment_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["augment_id"],
            ["augments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["comp_id"],
            ["comps.id"],
        ),
        sa.PrimaryKeyConstraint("comp_id", "augment_id"),
    )
    op.create_table(
        "comp_champions",
        sa.Column("comp_id", sa.Integer(), nullable=False),
        sa.Column("champion_id", sa.Integer(), nullable=False),
        sa.Column("is_carry", sa.Boolean(), nullable=False),
        sa.Column(
            "recommended_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["comp_id"],
            ["comps.id"],
        ),
        sa.PrimaryKeyConstraint("comp_id", "champion_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comp_champions")
    op.drop_table("comp_augments")
    op.drop_table("champion_item_builds")
    op.drop_table("comps")
    # ### end Alembic commands ###
